sudo: true
dist: trusty
install:
- sudo apt-get --yes install autoconf libtool nasm
- npm install --verbose
- wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
script:
- hugo
cache:
  directories:
  - node_modules
deploy:
  local-dir: public
  repo: EclipseFdn/openmobility.eclipse.org
  target-branch: gh-pages
  provider: pages
  keep-history: true
  skip-cleanup: true
  github_token: "$GITHUB_TOKEN"
  email: chris.guindon@eclipse-foundation.org
  name: Christopher Guindon
  on:
    branch: master
env:
  global:
    secure: FR3j9MyORu0dv68lL2xawuptbnVQBxAhh69s3YBfxZOm4HQs7CBcj7bzayq6IRbfFsYxZIpqOMn1t1ecee6jBBhAurV3iu5uXOr8s6PCuvv8z0N8P8/v4+pFCA6y6GayTriO+DBUTGiTuexUZ5Xear8Rq9no0PYHrDDTNl3kT3x8Vgbbf8dZJqVHd/jDVyXGIJcpS8Y+Qr1Inw07u1/nHxVPAXWrnSsYSHU8pHfsyUSP7nABMgG5FJGRw04CQlM4CSWXZ2+JZDWj7xiKPMwD7rtvyX7Lx/gzaYDaa+NiNRZoIBE0l6CJwkJSJHlUj/dX8ILokp9QL06TUUgSYiSy4C5iGRGE4xUzHFVkV6p8IAZ1EO8b7r5jeWkwcUS7zELw7maOS8/RUZg+g0Cg9FQU8AaQiRZBfrxWMEcH1BUuzdSmkMhdX4Yw07hRgHyLA0uomzbYTqjcZZ9Lgs8xfgM8Is3M3er41g4+BtPE6uN6HBwHnBytxcvh8sZq1ozOUWJyOUF1qi9tslEVeKft7gYFjAsf+bi0uUq9taY/Yaz9LChMg/EfPcRc/3EFuomxc78Y04KzAtWGcfMbDdnvRln7ZlVwNNp64E0imfvh8x6L86Y4BOBLFAaKzTDMUX4rZrxIb1JYZoFhu6yDGKh8Sx+bOFLGvQ6FKX1m58dE6bBzxSQ=
