baseurl = "https://eclipsefdn.github.io/openmobility.eclipse.org/"
DefaultContentLanguage = "en"
title = "The openMobility working group will drive the evolution and broad adoption of mobility modelling and simulation technologies." 
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
#googleAnalytics = ""
disableKinds = ["taxonomyTerm"]
themesDir = "node_modules/"

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = ""
  subtitle = ""
  seo_title_suffix = " | Eclipse openMobility Working Group | The Eclipse Foundation"
  keywords = ["Mobility modelling", "simulation technologies", "OpenMobility framework", "Mobility-as-a-Service"]
  logo = "images/logo/logo.png"
  styles = "css/styles.css"
# favicon = "o"
# share_img = ""
  gcse = "011805775785170369411:p3ec0igo0qq"
# subtheme = ""
  header_wrapper_class = "header-default-bg-img"
  js = "js/solstice.js"
# call_for_action_text = ""
# call_for_action_url = ""
# call_for_action_icon = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "chris.guindon@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 2

[[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 3

[[menu.main]]
    name = "Vision"
    url = "/vision/"
    weight = 4

[[menu.main]]
    name = "Technologies"
    url = "/technologies/"
    weight = 5

[[menu.main]]
    name = "Members"
    url = "/members/"
    weight = 6

[[menu.main]]
    name = "Working Group"
    url = "/working-group/"
    weight = 7